import React from 'react'





export default () => {

    const json = {
        "total_students": 317,
        "students": [
            { "scan_index": 1, "name": "TAMANNA", "rank": "1", "class": "B.Sc. (PS)" },
            { "scan_index": 2, "name": "ANKITA", "rank": "1", "class": "B.Sc. (ZH)" },
            { "scan_index": 3, "name": "ANTIM", "rank": "1", "class": "B.Sc. (ZH)" },
            { "scan_index": 4, "name": "KAJAL", "rank": "1", "class": "B.Sc. (ZH)" },
            { "scan_index": 5, "name": "SUPRIYA", "rank": "1", "class": "B.Sc. (ZH)" },
            { "scan_index": 6, "name": "SONAM", "rank": "1", "class": "B.Sc. (CH)" },
            { "scan_index": 7, "name": "PRIYA", "rank": "1", "class": "B.Sc. (ZH)" },
            { "scan_index": 8, "name": "HEENA", "rank": "1", "class": "B.Sc. (NM)" },
            { "scan_index": 9, "name": "SHIWANI", "rank": "1", "class": "B.Sc. (CH)" },
            { "scan_index": 10, "name": "KIRAN", "rank": "1", "class": "B.A" },
            { "scan_index": 11, "name": "NISHA", "rank": "1", "class": "B.Sc. (ZH)" },
            { "scan_index": 12, "name": "MANJU", "rank": "1", "class": "B.Sc. (ZH)" },
            { "scan_index": 13, "name": "SAKSHI", "rank": "1", "class": "B.Sc. (NM)" },
            { "scan_index": 14, "name": "ALKA", "rank": "1", "class": "B.Sc. (Med.)" },
            { "scan_index": 15, "name": "POOJA", "rank": "1", "class": "B.Sc. (MH)" },
            { "scan_index": 16, "name": "ANMOL", "rank": "1", "class": "B.Sc. (ZH)" },
            { "scan_index": 17, "name": "RINKI", "rank": "1", "class": "B.Sc. (MH)" },
            { "scan_index": 18, "name": "NIKITA", "rank": "1", "class": "B.Sc. (CH)" },
            { "scan_index": 19, "name": "ABHISHEK", "rank": "1", "class": "B.Sc. (CH)" },
            { "scan_index": 20, "name": "PRATHAM", "rank": "1", "class": "B.Sc. (MH)" },
            { "scan_index": 21, "name": "SANGEETA", "rank": "1", "class": "B.Sc. (PH)" },
            { "scan_index": 22, "name": "MAMTA", "rank": "1", "class": "B.Sc. (ZH)" },
            { "scan_index": 23, "name": "AMBIKA", "rank": "1", "class": "B.Sc. (MH)" },
            { "scan_index": 24, "name": "PRIYA", "rank": "1", "class": "B.Sc. (ZH)" },
            { "scan_index": 25, "name": "LATIKA", "rank": "1", "class": "B.Sc. (Med.)" },
            { "scan_index": 26, "name": "EKTA", "rank": "1", "class": "B.Sc. (MH)" },
            { "scan_index": 27, "name": "SUDHA", "rank": "1", "class": "B.COM.(Hons.)" },
            { "scan_index": 28, "name": "TANISHA", "rank": "1", "class": "B.Sc. (MH)" },
            { "scan_index": 29, "name": "POOJA", "rank": "1", "class": "B.Sc. (ZH)" },
            { "scan_index": 30, "name": "MONIKA", "rank": "1", "class": "B.Sc. (ZH)" },
            { "scan_index": 31, "name": "ANNU", "rank": "1", "class": "B.Sc. (ZH)" },
            { "scan_index": 32, "name": "ALPA", "rank": "1", "class": "B.Sc. (NM)" },
            { "scan_index": 33, "name": "MUSKNAN", "rank": "1", "class": "B.A." },
            { "scan_index": 34, "name": "PRITI", "rank": "1", "class": "B.Sc. (MH)" },
            { "scan_index": 35, "name": "DIKSHIKA", "rank": "1", "class": "B.Sc. (CH)" },
            { "scan_index": 36, "name": "TINKESH", "rank": "1", "class": "B.Sc. (NM)" },
            { "scan_index": 37, "name": "SUDHA", "rank": "1", "class": "B.Com. (H)" },
            { "scan_index": 38, "name": "SHEETAL", "rank": "1", "class": "B.Com." },
            { "scan_index": 39, "name": "PAYAL", "rank": "1", "class": "B.Sc. (PH)" },
            { "scan_index": 40, "name": "NEHA", "rank": "1", "class": "B.Com." },
            { "scan_index": 41, "name": "AARTI", "rank": "1", "class": "B.Com." },
            { "scan_index": 42, "name": "PREETI", "rank": "1", "class": "B.Com." },
            { "scan_index": 43, "name": "NISHA", "rank": "1", "class": "B.Com." },
            { "scan_index": 44, "name": "ASHA", "rank": "1", "class": "B.A" },
            { "scan_index": 45, "name": "MUSKAN YADAV", "rank": "1", "class": "B.COM." },
            { "scan_index": 46, "name": "HARSHITA", "rank": "1", "class": "B.A" },
            { "scan_index": 47, "name": "SNEHA", "rank": "1", "class": "B.TECH" },
            { "scan_index": 48, "name": "PRIYA", "rank": "1", "class": "B.Sc (ZH)" },
            { "scan_index": 49, "name": "EKTA", "rank": "1", "class": "B.Sc (MH)" },
            { "scan_index": 50, "name": "MANISHA", "rank": "1", "class": "B.COM.(Hons.)" },
            { "scan_index": 51, "name": "MAHAK", "rank": "1", "class": "B.A" },
            { "scan_index": 52, "name": "PREETI", "rank": "2", "class": "B.Sc. (MH)" },
            { "scan_index": 53, "name": "KASHISH", "rank": "2", "class": "B.Sc (MH)" },
            { "scan_index": 54, "name": "AHANA", "rank": "2", "class": "B.COM" },
            { "scan_index": 55, "name": "SAPNA", "rank": "2", "class": "B.Sc (CH)" },
            { "scan_index": 56, "name": "KAJAL", "rank": "2", "class": "BCA" },
            { "scan_index": 57, "name": "PRIYA", "rank": "2", "class": "B.Sc. (ZH)" },
            { "scan_index": 58, "name": "SAPNA", "rank": "2", "class": "B.Sc. (ZH)" },
            { "scan_index": 59, "name": "RAVINA", "rank": "2", "class": "B.Sc. Life Sci." },
            { "scan_index": 60, "name": "SANJANA", "rank": "2", "class": "B.Sc. (MATHS)" },
            { "scan_index": 61, "name": "ASHA", "rank": "2", "class": "ARTS" },
            { "scan_index": 62, "name": "GARGI", "rank": "2", "class": "B.A" },
            { "scan_index": 63, "name": "JYOTI", "rank": "2", "class": "B.Sc. (Med.)" },
            { "scan_index": 64, "name": "MONIKA", "rank": "2", "class": "B.Sc. (PH)" },
            { "scan_index": 65, "name": "EKTA", "rank": "2", "class": "B.Sc. (ZH)" },
            { "scan_index": 66, "name": "PRIYANKA", "rank": "2", "class": "B.A." },
            { "scan_index": 67, "name": "SUBHLATA", "rank": "2", "class": "B.Sc. (ZH)" },
            { "scan_index": 68, "name": "NISHITA", "rank": "2", "class": "B.Sc. (NM)" },
            { "scan_index": 69, "name": "NANCY", "rank": "2", "class": "B.Sc. (CH)" },
            { "scan_index": 70, "name": "YOGESH", "rank": "2", "class": "B.Sc. (NM)" },
            { "scan_index": 71, "name": "DEEPIKA", "rank": "2", "class": "B.Sc. (MH)" },
            { "scan_index": 72, "name": "NISHA", "rank": "2", "class": "B.Com" },
            { "scan_index": 73, "name": "PREETI", "rank": "2", "class": "B.A." },
            { "scan_index": 74, "name": "PREETI", "rank": "2", "class": "B.Sc. (CH)" },
            { "scan_index": 75, "name": "ANJALI", "rank": "2", "class": "B.TECH" },
            { "scan_index": 76, "name": "SHIKSHA", "rank": "2", "class": "B.Sc. (NM)" },
            { "scan_index": 77, "name": "DIKSHA", "rank": "2", "class": "B.Sc. (NM)" },
            { "scan_index": 78, "name": "ANUPRIYA", "rank": "2", "class": "B.Sc. (ZH)" },
            { "scan_index": 79, "name": "APURVA", "rank": "2", "class": "B.Sc. (CH)" },
            { "scan_index": 80, "name": "DEEPIKA", "rank": "2", "class": "B.Sc. (MH)" },
            { "scan_index": 81, "name": "PRIYA", "rank": "2", "class": "B.Com. (H)" },
            { "scan_index": 82, "name": "RAKHI", "rank": "2", "class": "BBA" },
            { "scan_index": 83, "name": "NANCY", "rank": "2", "class": "B.Com. (H)" },
            { "scan_index": 84, "name": "KHUSHI", "rank": "2", "class": "B.Sc. Life Science" },
            { "scan_index": 85, "name": "MUSKAN", "rank": "2", "class": "B.COM.(Hons.)" },
            { "scan_index": 86, "name": "RAKHI", "rank": "2", "class": "BBA" },
            { "scan_index": 87, "name": "ANNU", "rank": "2", "class": "B.Sc. (PH)" },
            { "scan_index": 88, "name": "BHUMI ARORA", "rank": "3", "class": "B.Sc. Life Science" },
            { "scan_index": 89, "name": "LALIT KUMARI", "rank": "3", "class": "B.Sc. (PHY.SCI.)" },
            { "scan_index": 90, "name": "KHUSHBOO", "rank": "3", "class": "B.Com." },
            { "scan_index": 91, "name": "MAYANK", "rank": "3", "class": "B.COM" },
            { "scan_index": 92, "name": "KAJAL", "rank": "3", "class": "BCA" },
            { "scan_index": 93, "name": "RENU", "rank": "3", "class": "B.Sc. Life Science" },
            { "scan_index": 94, "name": "PRIYA", "rank": "3", "class": "B.Sc. (MH)" },
            { "scan_index": 95, "name": "NIDHI GUPTA", "rank": "3", "class": "BCA" },
            { "scan_index": 96, "name": "GARIMA", "rank": "3", "class": "B.Sc. (Med.)" },
            { "scan_index": 97, "name": "HARSHITA", "rank": "3", "class": "B.A." },
            { "scan_index": 98, "name": "ANKITA", "rank": "3", "class": "B.Sc. (NM)" },
            { "scan_index": 99, "name": "LUCKY", "rank": "3", "class": "B.Sc. (Med.)" },
            { "scan_index": 100, "name": "NISHA", "rank": "3", "class": "B.Sc. (CH)" },
            { "scan_index": 101, "name": "BHARTI", "rank": "3", "class": "B.Sc. (Med.)" },
            { "scan_index": 102, "name": "PREETI", "rank": "3", "class": "B.Sc. (Med.)" },
            { "scan_index": 103, "name": "ASHA", "rank": "3", "class": "B.Com." },
            { "scan_index": 104, "name": "ANSHUM", "rank": "3", "class": "B.Sc. (ZH)" },
            { "scan_index": 105, "name": "NISHA", "rank": "3", "class": "B.Sc. (ZH)" },
            { "scan_index": 106, "name": "HEENA", "rank": "3", "class": "B.Com. (H)" },
            { "scan_index": 107, "name": "PRIYA", "rank": "3", "class": "B.Com." },
            { "scan_index": 108, "name": "MUSKAN", "rank": "3", "class": "B.Com. (H)" },
            { "scan_index": 109, "name": "NEHA", "rank": "3", "class": "B.Sc. (MH)" },
            { "scan_index": 110, "name": "NAVNEETA", "rank": "3", "class": "BCA" },
            { "scan_index": 111, "name": "CHETNA", "rank": "3", "class": "B.Sc. (MH)" },
            { "scan_index": 112, "name": "PRIYANKA", "rank": "3", "class": "B.Sc. (Med.)" },
            { "scan_index": 113, "name": "NIKITA", "rank": "3", "class": "B.Sc. (MH)" },
            { "scan_index": 114, "name": "SAKSHI", "rank": "3", "class": "ARTS (YOGA)" },
            { "scan_index": 115, "name": "ISHA", "rank": "3", "class": "B.A." },
            { "scan_index": 116, "name": "MONIKA", "rank": "3", "class": "B.Sc. (ZH)" },
            { "scan_index": 117, "name": "NAVEEN", "rank": "3", "class": "B.Sc. (ZH)" },
            { "scan_index": 118, "name": "SAPNA", "rank": "3", "class": "B.Sc. (CH)" },
            { "scan_index": 119, "name": "MANISHA", "rank": "3", "class": "B.Sc. (CH)" },
            { "scan_index": 120, "name": "RITIK", "rank": "3", "class": "B.Sc. (Med.)" },
            { "scan_index": 121, "name": "PRIYA", "rank": "3", "class": "B.Com." },
            { "scan_index": 122, "name": "TAMANNA", "rank": "3", "class": "B.Sc(PS)" },
            { "scan_index": 123, "name": "POONAM", "rank": "3", "class": "B.Sc. (PH)" },
            { "scan_index": 124, "name": "ADITYA", "rank": "4", "class": "B.Sc. (ZH)" },
            { "scan_index": 125, "name": "DEEPIKA", "rank": "4", "class": "B.Sc. (MH)" },
            { "scan_index": 126, "name": "RAHUL", "rank": "4", "class": "B.Sc. (MH)" },
            { "scan_index": 127, "name": "PRIYA", "rank": "4", "class": "B.Sc. (ZH)" },
            { "scan_index": 128, "name": "NEHA", "rank": "4", "class": "B.Sc. (CH)" },
            { "scan_index": 129, "name": "ANSHU", "rank": "4", "class": "B.COM.(Hons.)" },
            { "scan_index": 130, "name": "TAMANNA", "rank": "4", "class": "B.Sc. (ZH)" },
            { "scan_index": 131, "name": "VANSHIKA", "rank": "4", "class": "BCA" },
            { "scan_index": 132, "name": "ARUNA", "rank": "4", "class": "B.Sc. (CH)" },
            { "scan_index": 133, "name": "ANAMIKA", "rank": "4", "class": "B.Sc. (ZH)" },
            { "scan_index": 134, "name": "RIYA", "rank": "4", "class": "B.Sc. (PH)" },
            { "scan_index": 135, "name": "SAKSHI", "rank": "4", "class": "B.TECH" },
            { "scan_index": 136, "name": "MANISH", "rank": "4", "class": "BCA" },
            { "scan_index": 137, "name": "VISHAKHA", "rank": "4", "class": "B.Com." },
            { "scan_index": 138, "name": "PARTIMA", "rank": "4", "class": "B.Com." },
            { "scan_index": 139, "name": "ANSHU", "rank": "4", "class": "B.Com. (H)" },
            { "scan_index": 140, "name": "NEHA", "rank": "4", "class": "ARTS" },
            { "scan_index": 141, "name": "KHUSHI", "rank": "4", "class": "B.Sc. (Life Sci.)" },
            { "scan_index": 142, "name": "TANISHA", "rank": "4", "class": "B.Sc. (MH)" },
            { "scan_index": 143, "name": "TANNU", "rank": "4", "class": "B.Sc. (ZH)" },
            { "scan_index": 144, "name": "PRIYANKA", "rank": "4", "class": "B.Sc. (Med.)" },
            { "scan_index": 145, "name": "SUSHMA", "rank": "4", "class": "B.Sc. (Med.)" },
            { "scan_index": 146, "name": "KHUSHI", "rank": "4", "class": "B.Sc.(Phy Sci.)" },
            { "scan_index": 147, "name": "ANITA", "rank": "4", "class": "B.Sc. (ZH)" },
            { "scan_index": 148, "name": "PREETI", "rank": "4", "class": "B.Sc. (ZH)" },
            { "scan_index": 149, "name": "TAMANNA", "rank": "4", "class": "B.Sc. (ZH)" },
            { "scan_index": 150, "name": "ANJALI", "rank": "4", "class": "B.Sc. (ZH)" },
            { "scan_index": 151, "name": "SONIYA", "rank": "4", "class": "B.Sc. (MH)" },
            { "scan_index": 152, "name": "SANEH", "rank": "4", "class": "B.Sc. (MH)" },
            { "scan_index": 153, "name": "SANDHYA", "rank": "4", "class": "B.Sc. (NM)" },
            { "scan_index": 154, "name": "KASHISH", "rank": "4", "class": "B.Sc. (MH)" },
            { "scan_index": 155, "name": "KHUSHBU", "rank": "4", "class": "B.Sc. (CH)" },
            { "scan_index": 156, "name": "ISHU", "rank": "4", "class": "B.Sc. (ZH)" },
            { "scan_index": 157, "name": "PINKI", "rank": "4", "class": "B.Sc. (NM)" },
            { "scan_index": 158, "name": "MANISHA", "rank": "4", "class": "B.Sc. (MH)" },
            { "scan_index": 159, "name": "JYOTI", "rank": "4", "class": "B.A." },
            { "scan_index": 160, "name": "RITIKA", "rank": "4", "class": "B.Sc. (ZH)" },
            { "scan_index": 161, "name": "TAMANA YADAV", "rank": "5", "class": "ZOO.(Hons.)" },
            { "scan_index": 162, "name": "SANGAM", "rank": "5", "class": "B.Sc. (CH)" },
            { "scan_index": 163, "name": "KHUSHI", "rank": "5", "class": "B.Sc. (ZH)" },
            { "scan_index": 164, "name": "JYOTI", "rank": "5", "class": "ARTS(YOGA)" },
            { "scan_index": 165, "name": "SHIWANI", "rank": "5", "class": "B.Sc. (ZH)" },
            { "scan_index": 166, "name": "NEHA", "rank": "5", "class": "B.Sc. (Medi.)" },
            { "scan_index": 167, "name": "SHIWANI", "rank": "5", "class": "B.Sc. (Med.)" },
            { "scan_index": 168, "name": "TANISHA", "rank": "5", "class": "B.Sc. (CH)" },
            { "scan_index": 169, "name": "NISHA", "rank": "5", "class": "B.Sc. (MH)" },
            { "scan_index": 170, "name": "DEEPIKA", "rank": "5", "class": "B.Sc. (ZH)" },
            { "scan_index": 171, "name": "PREETI", "rank": "5", "class": "B.Sc. (ZH)" },
            { "scan_index": 172, "name": "EKTA", "rank": "5", "class": "B.A." },
            { "scan_index": 173, "name": "TAMANNA", "rank": "5", "class": "B.Sc. (ZH)" },
            { "scan_index": 174, "name": "MAHIMA", "rank": "5", "class": "B.Sc. (ZH)" },
            { "scan_index": 175, "name": "NEHA", "rank": "5", "class": "B.Sc. (MH)" },
            { "scan_index": 176, "name": "VANSHIKA", "rank": "5", "class": "BCA" },
            { "scan_index": 177, "name": "RITU", "rank": "5", "class": "B.Sc. (NM)" },
            { "scan_index": 178, "name": "SANJANA", "rank": "5", "class": "B.Sc. (MH)" },
            { "scan_index": 179, "name": "ANKITA", "rank": "5", "class": "B.Sc. (NM)" },
            { "scan_index": 180, "name": "MAMTA", "rank": "5", "class": "B.Sc. (ZH)" },
            { "scan_index": 181, "name": "SONAM", "rank": "5", "class": "B.Sc. (PH)" },
            { "scan_index": 182, "name": "SARGAM", "rank": "5", "class": "B.Sc. (PH)" },
            { "scan_index": 183, "name": "ANKITA", "rank": "5", "class": "B.Sc. (MH)" },
            { "scan_index": 184, "name": "TANNU", "rank": "5", "class": "B.Sc.(Phy.Sci.)" },
            { "scan_index": 185, "name": "TANISHA", "rank": "5", "class": "B.COM" },
            { "scan_index": 186, "name": "LAXMI", "rank": "5", "class": "B.Com." },
            { "scan_index": 187, "name": "POONAM", "rank": "5", "class": "B.Com." },
            { "scan_index": 188, "name": "SHIWANI", "rank": "5", "class": "B.Com." },
            { "scan_index": 189, "name": "PRIYANKA", "rank": "5", "class": "B.Com." },
            { "scan_index": 190, "name": "CHANCHAL", "rank": "5", "class": "B.Sc. (MH)" },
            { "scan_index": 191, "name": "SNEHA", "rank": "5", "class": "B.Com. (H)" },
            { "scan_index": 192, "name": "SUNITA", "rank": "5", "class": "B.Sc. (CH)" },
            { "scan_index": 193, "name": "ANJALI", "rank": "5", "class": "B.Sc. (ZH)" },
            { "scan_index": 194, "name": "PRIYA", "rank": "5", "class": "B.Sc. (ZH)" },
            { "scan_index": 195, "name": "PRIYAKA", "rank": "5", "class": "B.Sc. (ZH)" },
            { "scan_index": 196, "name": "YACHANA", "rank": "5", "class": "B.Sc. (ZH)" },
            { "scan_index": 197, "name": "SARITA", "rank": "6", "class": "B.Sc. (ZH)" },
            { "scan_index": 198, "name": "TAMANNA", "rank": "6", "class": "B.COM" },
            { "scan_index": 199, "name": "KHUSHI", "rank": "6", "class": "B.Sc. (Phy.Sci.)" },
            { "scan_index": 200, "name": "ISHU", "rank": "6", "class": "B.A." },
            { "scan_index": 201, "name": "NIKITA", "rank": "6", "class": "B.Sc (PH)" },
            { "scan_index": 202, "name": "HITESH", "rank": "6", "class": "B.Sc (PH)" },
            { "scan_index": 203, "name": "NEHA", "rank": "6", "class": "B.A" },


            { "scan_index": 204, "name": "PREETI", "rank": "6", "class": "B.COM.(Hons.)" },
            { "scan_index": 205, "name": "MONIKA", "rank": "6", "class": "B.Com." },
            { "scan_index": 206, "name": "NISHA", "rank": "6", "class": "B.Sc. (Medi.)" },
            { "scan_index": 207, "name": "POOJA", "rank": "6", "class": "B.Sc. (MH)" },
            { "scan_index": 208, "name": "POOJA", "rank": "6", "class": "B.Sc. (NM)" },
            { "scan_index": 209, "name": "ANJALI", "rank": "6", "class": "B.Sc. (ZH)" },
            { "scan_index": 210, "name": "PRIYA", "rank": "6", "class": "B.COM" },
            { "scan_index": 211, "name": "ARPANA", "rank": "6", "class": "BBA" },
            { "scan_index": 212, "name": "MAMTA", "rank": "6", "class": "B.Sc. (ZH)" },
            { "scan_index": 213, "name": "ANKITA", "rank": "6", "class": "B.Sc. (PH)" },
            { "scan_index": 214, "name": "MUSKAN", "rank": "6", "class": "B.A" },
            { "scan_index": 215, "name": "DIVYA", "rank": "6", "class": "B.Sc. (ZH)" },
            { "scan_index": 216, "name": "REENA", "rank": "6", "class": "B.Sc. (ZH)" },
            { "scan_index": 217, "name": "NEHA", "rank": "6", "class": "B.A." },
            { "scan_index": 218, "name": "MONIKA", "rank": "6", "class": "B.Sc. (PH)" },
            { "scan_index": 219, "name": "PRIYA", "rank": "6", "class": "B.Sc. (ZH)" },
            { "scan_index": 220, "name": "KAVITA", "rank": "6", "class": "BCA" },
            { "scan_index": 221, "name": "PRIYA", "rank": "6", "class": "B.Com." },
            { "scan_index": 222, "name": "ANAMIKA", "rank": "7", "class": "B.Com." },
            { "scan_index": 223, "name": "MANSI", "rank": "7", "class": "B.Sc. (MH)" },
            { "scan_index": 224, "name": "KOMAL", "rank": "7", "class": "B.Sc. (CH)" },
            { "scan_index": 225, "name": "KAVITA", "rank": "7", "class": "BCA" },
            { "scan_index": 226, "name": "SANGAM", "rank": "7", "class": "B.Sc. (CH)" },
            { "scan_index": 227, "name": "KUSUM", "rank": "7", "class": "B.Sc. (ZH)" },
            { "scan_index": 228, "name": "PINKI", "rank": "7", "class": "B.Sc. (CH)" },
            { "scan_index": 229, "name": "RIYA", "rank": "7", "class": "B.Sc. (MED.)" },
            { "scan_index": 230, "name": "DIKSHA", "rank": "7", "class": "B.A" },
            { "scan_index": 231, "name": "MANISHA", "rank": "7", "class": "B.A" },
            { "scan_index": 232, "name": "SHIVATI", "rank": "7", "class": "B.A" },
            { "scan_index": 233, "name": "MAHEK SHARMA", "rank": "7", "class": "BCA" },
            { "scan_index": 234, "name": "KAVITA", "rank": "7", "class": "B.Sc. (NM)" },
            { "scan_index": 235, "name": "SONIYA", "rank": "7", "class": "B.Sc. (CH)" },
            { "scan_index": 236, "name": "KHUSHI", "rank": "7", "class": "B.Sc. (Med.)" },
            { "scan_index": 237, "name": "NIKITA", "rank": "7", "class": "B.Sc. (CH)" },
            { "scan_index": 238, "name": "NIDHI", "rank": "7", "class": "B.Sc. (Med.)" },
            { "scan_index": 239, "name": "ANTIMA", "rank": "7", "class": "B.Sc. (ZH)" },
            { "scan_index": 240, "name": "DEV", "rank": "7", "class": "BCA" },
            { "scan_index": 241, "name": "KIRAN", "rank": "8", "class": "B.Sc. (ZH)" },
            { "scan_index": 242, "name": "ANSHU", "rank": "8", "class": "B.Sc. (MH)" },
            { "scan_index": 243, "name": "SIMRAN", "rank": "8", "class": "BCA" },
            { "scan_index": 244, "name": "GARIMA", "rank": "8", "class": "B.Sc. (ZH)" },
            { "scan_index": 245, "name": "HIMANSHU", "rank": "8", "class": "B.COM." },
            { "scan_index": 246, "name": "PAYAL", "rank": "8", "class": "B.Sc(NM)" },
            { "scan_index": 247, "name": "PRIYANKA", "rank": "8", "class": "B.A." },
            { "scan_index": 248, "name": "NARESH", "rank": "8", "class": "B.Sc. (ZH)" },
            { "scan_index": 249, "name": "PALAK", "rank": "8", "class": "B.Sc. (ZH)" },
            { "scan_index": 250, "name": "MANISHA", "rank": "8", "class": "B.Sc. (CH)" },
            { "scan_index": 251, "name": "KANCHAN", "rank": "8", "class": "B.Sc. (CH)" },
            { "scan_index": 252, "name": "PRIYA", "rank": "8", "class": "B.Sc. (Med.)" },
            { "scan_index": 253, "name": "PINKI", "rank": "8", "class": "B.Sc. (NM)" },
            { "scan_index": 254, "name": "NEERU", "rank": "8", "class": "B.Sc. (Med.)" },
            { "scan_index": 255, "name": "PRIYANKA", "rank": "8", "class": "B.Sc. (CH)" },
            { "scan_index": 256, "name": "MEENU", "rank": "8", "class": "B.Sc. (ZH)" },
            { "scan_index": 257, "name": "SANIYA", "rank": "8", "class": "B.A" },
            { "scan_index": 258, "name": "ANAMIKA", "rank": "8", "class": "B.COM" },
            { "scan_index": 259, "name": "MANISH", "rank": "8", "class": "BCA" },
            { "scan_index": 260, "name": "ANUSHKA", "rank": "8", "class": "B.Sc. Life Sci." },
            { "scan_index": 261, "name": "TAMANNA", "rank": "8", "class": "B.Sc. (Phy.Sci)" },
            { "scan_index": 262, "name": "RITIKA", "rank": "8", "class": "B.Sc. (ZH)" },
            { "scan_index": 263, "name": "KAVITA", "rank": "8", "class": "BCA" },
            { "scan_index": 264, "name": "PREETI", "rank": "8", "class": "B.Sc. Maths" },
            { "scan_index": 265, "name": "ANTIMA", "rank": "8", "class": "B.Sc. (ZH)" },
            { "scan_index": 266, "name": "CHETAN", "rank": "8", "class": "B.Com. (H)" },
            { "scan_index": 267, "name": "YASHIKA", "rank": "8", "class": "B.Sc. (ZH)" },
            { "scan_index": 268, "name": "NEHA", "rank": "8", "class": "B.Sc. (ZH)" },
            { "scan_index": 269, "name": "PRIYA", "rank": "9", "class": "B.Sc. (CH)" },
            { "scan_index": 270, "name": "KIRTI", "rank": "9", "class": "B.Sc. (ZH)" },
            { "scan_index": 271, "name": "DEEPIKA", "rank": "9", "class": "B.Sc. (ZH)" },
            { "scan_index": 272, "name": "PRIYA", "rank": "9", "class": "B.Sc. (CH)" },
            { "scan_index": 273, "name": "NISHU", "rank": "9", "class": "B.Sc. (Med.)" },
            { "scan_index": 274, "name": "VARSHA", "rank": "9", "class": "B.Sc. (Med.)" },
            { "scan_index": 275, "name": "KIRAN", "rank": "9", "class": "ARTS" },
            { "scan_index": 276, "name": "SHEETAL", "rank": "9", "class": "B.Sc. (NM)" },
            { "scan_index": 277, "name": "DIVYA", "rank": "9", "class": "B.COM" },
            { "scan_index": 278, "name": "SANIYA", "rank": "9", "class": "B.Sc. (PH)" },
            { "scan_index": 279, "name": "VISHA", "rank": "9", "class": "B.Sc. (PH)" },
            { "scan_index": 280, "name": "DIVYA", "rank": "9", "class": "B.Sc. (CH)" },
            { "scan_index": 281, "name": "NISHA", "rank": "9", "class": "B.A." },
            { "scan_index": 282, "name": "SIMRAN", "rank": "9", "class": "BCA" },
            { "scan_index": 283, "name": "TAMANNA", "rank": "9", "class": "B.Sc. (Life Sci.)" },
            { "scan_index": 284, "name": "AMITA", "rank": "9", "class": "B.Sc. (MH)" },
            { "scan_index": 285, "name": "PREETI", "rank": "9", "class": "B.Sc. (NM)" },
            { "scan_index": 286, "name": "TAMANNA", "rank": "9", "class": "ARTS" },
            { "scan_index": 287, "name": "ANUP", "rank": "9", "class": "B.Sc. (ZH)" },
            { "scan_index": 288, "name": "RIYA", "rank": "9", "class": "B.Com." },
            { "scan_index": 289, "name": "MUSKAN", "rank": "9", "class": "B.Sc. (CH)" },
            { "scan_index": 290, "name": "MANISHA", "rank": "9", "class": "B.Sc. (MH)" },
            { "scan_index": 291, "name": "RAJBALA", "rank": "9", "class": "B.Sc. (MH)" },
            { "scan_index": 292, "name": "ANJALI", "rank": "9", "class": "B.Sc(NM)" },
            { "scan_index": 293, "name": "PAYAL", "rank": "9", "class": "B.COM.(Hons.)" },
            { "scan_index": 294, "name": "PRIYA", "rank": "9", "class": "B.Sc (NM)" },
            { "scan_index": 295, "name": "JYOTI", "rank": "10", "class": "ARTS" },
            { "scan_index": 296, "name": "RACHANA", "rank": "10", "class": "B.Sc. (ZH)" },
            { "scan_index": 297, "name": "ANSHU", "rank": "10", "class": "B.Sc(NM)" },
            { "scan_index": 298, "name": "PREETI", "rank": "10", "class": "B.Sc.(Med.)" },
            { "scan_index": 299, "name": "KOMAL", "rank": "10", "class": "B.Sc. (CH)" },
            { "scan_index": 300, "name": "SHIKSHA", "rank": "10", "class": "B.Sc. (ZH)" },
            { "scan_index": 301, "name": "PRIYA", "rank": "10", "class": "B.Sc (NM)" },
            { "scan_index": 302, "name": "MONIKA", "rank": "10", "class": "B.Sc. (NM)" },
            { "scan_index": 303, "name": "RITU", "rank": "10", "class": "B.Sc. (CH)" },
            { "scan_index": 304, "name": "NISHA", "rank": "10", "class": "B.Sc. (MH)" },
            { "scan_index": 305, "name": "LUCKY", "rank": "10", "class": "B.Sc. Med." },
            { "scan_index": 306, "name": "JYOTI", "rank": "10", "class": "B.Com." },
            { "scan_index": 307, "name": "HEENA", "rank": "10", "class": "B.Com." },
            { "scan_index": 308, "name": "BHUMIKA", "rank": "10", "class": "B.A" },
            { "scan_index": 309, "name": "MANISHA", "rank": "10", "class": "B.A" },
            { "scan_index": 310, "name": "MUSKAN", "rank": "10", "class": "B.Sc. (PH)" },
            { "scan_index": 311, "name": "SUDHA", "rank": "10", "class": "B.Sc. (ZH)" },
            { "scan_index": 312, "name": "AHANA", "rank": "10", "class": "B.Sc. (ZH)" },
            { "scan_index": 313, "name": "ANJALI", "rank": "10", "class": "B.Sc. (Medi.)" },
            { "scan_index": 314, "name": "FATEH SINGH", "rank": "10", "class": "B.Sc. (MH)" }

        ]
    }
    return (
        <div className="w-full">
            <div className="imported-block my-2">
                <header className="mb-10 text-center">
                    <h1 className="text-2xl font-normal tracking-tight mb-2">&nbsp;</h1>
                </header>

                <main className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-7 gap-4 max-w-[1400px] mx-auto">
                    {json.students.map((student, index) => (
                        <div
                            key={student.scan_index || index}
                            className="bg-white border border-[#e5e5e5] rounded-md overflow-hidden text-center transition-all duration-200 ease-in-out hover:-translate-y-1 hover:border-[#a3a3a3]"
                        >
                            <div className="overflow-hidden w-full h-[190px] bg-[#f0f0f0]">
                                <img
                                    className="w-full h-full object-contain block transition-transform duration-200 ease-in-out group-hover:scale-105"
                                    src={"https://admin.yaduvanshigroup.edu.in/uploads/college-top/top-10-ug/" + student.scan_index + ".jpg"}
                                    alt={student.name}
                                />
                            </div>
                            <div className="p-3">
                                <div className="text-sm font-medium text-[#1a1a1a] mb-1 whitespace-nowrap overflow-hidden text-ellipsis">
                                    {student.name}
                                </div>
                                <div className="text-[11px] text-[#666666] whitespace-nowrap overflow-hidden text-ellipsis">
                                    RANK: <span class="font-semibold text-black">{student.rank}</span>
                                </div>
                                <div className="text-[11px] text-[#666666] whitespace-nowrap overflow-hidden text-ellipsis">
                                    Class: <span class="font-semibold text-black">{student.class}</span>
                                </div>
                            </div>
                        </div>
                    ))}
                </main>
            </div>
        </div>
    )
}
